version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql

  nextjs:
    build: .
    container_name: nextjs
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:password@localhost:3306/real_estate

volumes:
  mysql_data:
