version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
